name = "digital-circuit-sim"
compatibility_date = "2024-01-27"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "VISITOR_DB"
database_name = "digital-circuit"
database_id = "30cdd907-9902-4bee-88ee-73901a1609f2"
